# Generated by Django 4.2.6 on 2024-09-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrimind', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologicalCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='psychological_conditions',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='psychological_conditions',
            field=models.ManyToManyField(to='nutrimind.psychologicalcondition'),
        ),
    ]
