# Generated by Django 4.2.6 on 2024-09-25 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrimind', '0003_recommendation_psychological_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='user_profile',
        ),
    ]
