# Generated by Django 4.2.6 on 2024-09-25 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrimind', '0004_remove_recommendation_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nutrimind.userprofile'),
        ),
    ]
