# Generated by Django 4.2.6 on 2024-09-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrimind', '0005_recommendation_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='user_profile',
        ),
    ]
