# Generated by Django 4.2.6 on 2024-09-28 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrimind', '0006_remove_recommendation_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='psychological_conditions',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='psychological_condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutrimind.psychologicalcondition'),
        ),
    ]
